#!/bin/bash
###############################################################################
# Cloud-init bootstrap for the Ariadne single-EC2 demo deployment.
#
# Runs ONCE on first boot. Streams progress to /var/log/user-data.log so you
# can `sudo tail -f /var/log/user-data.log` from SSH if anything goes wrong.
#
# What it does, in order:
#   1. Update the base AL2023 image
#   2. Install docker, docker compose plugin, git
#   3. Enable + start Docker, add ec2-user to the docker group
#   4. Clone the repo into /home/ec2-user/ariadne
#   5. Resolve this EC2's public DNS from the instance metadata service
#   6. Write a .env file that points the frontend build at that public URL
#   7. `docker compose up -d --build` — the whole stack
###############################################################################
set -euo pipefail
exec > >(tee /var/log/user-data.log) 2>&1

REPO_URL="${repo_url}"
REPO_BRANCH="${repo_branch}"
APP_DIR="/home/ec2-user/ariadne"

echo "[user-data] === Phase 1: system packages ==="
dnf update -y
# Don't install "curl" — AL2023 ships curl-minimal, and dnf can't have both
# installed at once (they file-conflict). curl-minimal supports -fsSL / -X / -H
# which is everything this script and the docker-compose builds need.
dnf install -y docker git

echo "[user-data] === Phase 2: docker compose plugin ==="
mkdir -p /usr/local/lib/docker/cli-plugins
curl -fsSL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

echo "[user-data] === Phase 3: enable docker, add ec2-user to group ==="
systemctl enable --now docker
usermod -aG docker ec2-user

echo "[user-data] === Phase 4: clone repo ==="
sudo -u ec2-user git clone --branch "$${REPO_BRANCH}" "$${REPO_URL}" "$${APP_DIR}"

echo "[user-data] === Phase 5: resolve public DNS via IMDSv2 ==="
TOKEN=$(curl -fsSL -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 60")
PUBLIC_DNS=$(curl -fsSL -H "X-aws-ec2-metadata-token: $${TOKEN}" \
  http://169.254.169.254/latest/meta-data/public-hostname)
PUBLIC_IP=$(curl -fsSL -H "X-aws-ec2-metadata-token: $${TOKEN}" \
  http://169.254.169.254/latest/meta-data/public-ipv4)
echo "[user-data] public-dns=$${PUBLIC_DNS}  public-ip=$${PUBLIC_IP}"

echo "[user-data] === Phase 6: write .env for compose ==="
cat > "$${APP_DIR}/lineage-platform/.env" <<ENV
# Generated by AWS user-data — do not edit by hand, it's overwritten on rebuild.
# Next.js inlines NEXT_PUBLIC_* at BUILD time, so this only takes effect on
# `docker compose build` / `up --build`.
NEXT_PUBLIC_GATEWAY_URL=http://$${PUBLIC_IP}:8000
CORS_ALLOWED_ORIGINS=http://$${PUBLIC_IP}:3000,http://$${PUBLIC_DNS}:3000
ENV
chown ec2-user:ec2-user "$${APP_DIR}/lineage-platform/.env"

echo "[user-data] === Phase 7: prepare uploads dir with permissive perms ==="
# The gateway container runs as a non-root `app` user but the host-mounted
# uploads dir is created by root (this script). Without explicit perms the
# gateway hits PermissionError trying to create per-upload subdirs.
# chmod 777 is fine here: the directory is reachable only through the
# gateway's own /parse/upload endpoint, behind the security group, and the
# instance is single-tenant.
mkdir -p "$${APP_DIR}/lineage-platform/uploads"
chmod 777 "$${APP_DIR}/lineage-platform/uploads"

echo "[user-data] === Phase 8: docker compose up -d --build ==="
# user-data runs as root, which has docker access directly. The ec2-user is
# in the docker group too (added above), so they can `docker ps` after they
# SSH in (a fresh login session picks up the group).
cd "$${APP_DIR}/lineage-platform"
docker compose up -d --build

echo "[user-data] === Done. Stack is starting up — give it 2-3 more minutes for healthchecks. ==="
echo "[user-data] Frontend: http://$${PUBLIC_IP}:3000"
echo "[user-data] Gateway:  http://$${PUBLIC_IP}:8000/health"
